stages:
  - check
  - build
  - deploy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonar-check:
  stage: check
  image: maven:3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=chibeg_unirio_microsservico
  only:
    - main

build:
  stage: build
  image: maven:3.8.3-openjdk-17
  artifacts:
    paths:
      - target/
  script:
    - mvn clean verify -Dsonar.skip=true -DskipTests=true install
  only:
    - main

aws-deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
   - aws deploy push --application-name ES2-microsservico --s3-location s3://es2-microsservico-bucket/nomeMicrosservico.zip --source .
   - aws deploy create-deployment --application-name ES2-microsservico --deployment-group-name ES2-microsservico-deploy --s3-location bucket=es2-microsservico-bucket,key=nomeMicrosservico.zip,bundleType=zip
  only:
    - main
  dependencies: 
    - build
