stages:
  - check
  - build
  - deploy

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

sonar-check:
  stage: check
  image: maven:3-openjdk-17
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.projectKey=JopeCys_scb-equipamentos
  only:
    - main
    - develop

build:
  stage: build
  image: maven:3.8.3-openjdk-17
  artifacts:
    paths:
      - target/
  script:
    - mvn clean verify -Dsonar.skip=true -DskipTests=true install
  only:
    - main

# aws-deploy:
#   stage: deploy
#   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#   script:
#    - aws deploy push --application-name ES2-microsservico --s3-location s3://es2-microsservico-bucket/base.zip --source . # TROCAR O NOME DO BUCKET E DO ZIP
#    - aws deploy create-deployment --application-name ES2-microsservico --deployment-group-name ES2-microsservico-deploy --s3-location bucket=es2-microsservico-bucket,key=base.zip,bundleType=zip
#     # TROCAR ACIMA O NOME DA APLICAÇÃO, NOME DO DEPLOYMENT GROUP, NOME DO BUCKET E NOME DO ZIP
#   only:
#     - main
#   dependencies: 
#     - build

    
